name: PR Agent Review
on: 
  pull_request:
    types: [opened, reopened, synchronize]
  issue_comment:
    types: [created]

jobs:
  pr_agent_job:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: read
    steps:
      - name: Run PR Agent
        uses: Codium-ai/pr-agent@main
        env: 
          CONFIG.GIT_PROVIDER: github
          CONFIG.MODEL: "openai/gpt-oss-20b"
          CONFIG.FALLBACK_MODELS: "['wen/qwen3.8-27b', 'openai/gpt-oss-120b']"

          GROQ.API_KEY: ${{ secrets.GROQ_API_KEY }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}

          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB.PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_TOKEN }}

          CONFIG.RESPONSE_LANGUAGE: "ru-RU"
          PR_DESCRIPTION.PUBLISH_DESCRIPTION_AS_COMMNENT: true
          PR_AGENT.PR_ACTIONS: "review,describe"
          
          
